---
- name: Install of Docker
  become: yes
  hosts: all

  tasks:

    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      with_items:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release 

    - name: Make Directory For GPG
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0775

    - name: Download of GPG
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings

    - name: Dearmor
      shell:
        "gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/gpg"

    - name: Check the Architecture
      shell: |
        dpkg --print-architecture
      register: linux_arch

    - name: Add Repository Into Source List
      apt_repository:
        repo: "deb [arch={{ linux_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker.list
    
    - name: Delete the Old GPG
      file:
        state:  absent
        path:   /etc/apt/keyrings/gpg

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Enable Docker In Systemd
      systemd:
        state: started
        name: docker
        enabled: true
